a lot of changes...

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,7 +9,7 @@ os:
 
 before_install:
   if ! command -v bash &> /dev/null; then
-    echo "[!] Error: Bash is not found." && exit 1
+    echo "[!] Error: GNU Bash is not found." && exit 1
   fi
 
   echo "[*] Using $(bash --version | head -n 1)."
diff --git a/tum b/tum
--- a/tum
+++ b/tum
@@ -34,41 +34,41 @@ LANG="C"
 ##
 ## `tum-bash` version:
 ##
-declare -r VERSION="1.2.2-stable"
+readonly VERSION="1.2.3-stable"
 
 ##
 ## ANSI Color codes and text formating:
 ##
-declare -r BLACK="\033[90m"
-declare -r WHITE="\033[97m"
-declare -r YELLOW="\033[93m"
-declare -r ORANGE="\033[38;5;214m"
-declare -r BLUE="\033[94m"
-declare -r CYAN="\e[0;36m"
-declare -r PURPLE="\033[95m"
-declare -r GREEN="\033[92m"
-declare -r RED="\033[91m"
+readonly BLACK="\033[90m"
+readonly WHITE="\033[97m"
+readonly YELLOW="\033[93m"
+readonly ORANGE="\033[38;5;214m"
+readonly BLUE="\033[94m"
+readonly CYAN="\e[0;36m"
+readonly PURPLE="\033[95m"
+readonly GREEN="\033[92m"
+readonly RED="\033[91m"
 
-declare -r BG_BLACK="\033[40m"
-declare -r BG_RED="\033[41m"
-declare -r BG_GREEN="\033[42m"
-declare -r BG_ORANGE="\033[43m"
-declare -r BG_BLUE="\033[44m"
-declare -r BG_MAGENTA="\033[105m"
-declare -r BG_CYAN="\033[46m"
-declare -r BG_WHITE="\033[47m"
+readonly BG_BLACK="\033[40m"
+readonly BG_RED="\033[41m"
+readonly BG_GREEN="\033[42m"
+readonly BG_ORANGE="\033[43m"
+readonly BG_BLUE="\033[44m"
+readonly BG_MAGENTA="\033[105m"
+readonly BG_CYAN="\033[46m"
+readonly BG_WHITE="\033[47m"
 
-declare -r BOLD="\033[1m"
-declare -r UNDERLINE="\033[4m"
-declare -r REVERSED="\033[7m"
-declare -r ITALIC="\033[3m"
-declare -r CROSSED_OUT="\033[9m"
-declare -r RESET="\033[0m"
+readonly BOLD="\033[1m"
+readonly UNDERLINE="\033[4m"
+readonly REVERSED="\033[7m"
+readonly ITALIC="\033[3m"
+readonly CROSSED_OUT="\033[9m"
+readonly RESET="\033[0m"
 
 ##
 ## Supported Package Managers:
 ##
-declare -r SUPPORTED_PMS=(
+readonly SUPPORTED_PMS=(
     "apt"                          # https://wiki.debian.org/Apt
     "apt-get"                      # https://manpages.debian.org/bookworm/apt/apt-get.8.en.html
     "apt-cache"                    # https://manpages.debian.org/bookworm/apt/apt-cache.8.en.html
@@ -108,7 +108,7 @@ declare -r SUPPORTED_PMS=(
 ##
 ## Supported Initialization Systems:
 ##
-declare -r SUPPORTED_INITS=(
+readonly SUPPORTED_INITS=(
     "sysvinit"   # https://wiki.gentoo.org/wiki/Sysvinit
     "openrc"     # https://wiki.gentoo.org/wiki/OpenRC
     "s6"         # https://skarnet.org/software/s6/
@@ -121,7 +121,7 @@ declare -r SUPPORTED_INITS=(
 ##
 ## Supported UNIX Distributions:
 ##
-declare -r DEBIAN_BASED=(
+readonly DEBIAN_BASED=(
     # The universal operating system.
     # <https://www.debian.org/>
 
@@ -157,7 +157,7 @@ declare -r DEBIAN_BASED=(
     "klikit" "tupiserver" "geolivre" "dizinha" "ankur" "linuxlte" "esware" "progeny" "liis" "muriqui" "loco"
 )
 
-declare -r ARCH_BASED=(
+readonly ARCH_BASED=(
     # A simple, lightweight distribution.
     # <https://www.archlinux.org/>
 
@@ -167,14 +167,14 @@ declare -r ARCH_BASED=(
     "kdemar" "archie" "faunos" "firefly" "linuxgamers" "kahelos" "netrunner" "ctkarch" "bridge" "sonar" "poliarch" "antergos"
 )
 
-declare -r ALPINE_BASED=(
+readonly ALPINE_BASED=(
     # Small. Simple. Secure.
     # <https://www.alpinelinux.org/>
 
     "alpine" "postmarket"
 )
 
-declare -r GENTOO_BASED=(
+readonly GENTOO_BASED=(
     # Welcome to Gentoo, a highly flexible, source-based Linux distribution.
     # <https://www.gentoo.org/>
 
@@ -184,21 +184,21 @@ declare -r GENTOO_BASED=(
     "gentooth" "mayix" "bicom" "bintoo" "phaeronix" "flash" "vlos" "systemrescue" "litrix" "iollix"
 )
 
-declare -r VOID_BASED=(
+readonly VOID_BASED=(
     # Void is a general purpose operating system, based on the monolithic Linux kernel.
     # <https://www.voidlinux.org/>
 
     "void" "argon" "shikake" "pristine" "projecttrident"
 )
 
-declare -r DRAGORA_BASED=(
+readonly DRAGORA_BASED=(
     # Stable. Secure. Reliable.
     # <https://www.dragora.org/>
 
     "dragora"
 )
 
-declare -r SLACKWARE_BASED=(
+readonly SLACKWARE_BASED=(
     # The Slackware Linux Project.
     # <http://www.slackware.com/>
 
@@ -209,7 +209,7 @@ declare -r SLACKWARE_BASED=(
     "saxenos" "nonux" "whoppix" "freepia" "slax" "supergamer" "vector" "plamo" "sentryfirewall"
 )
 
-declare -r REDHAT_BASED=(
+readonly REDHAT_BASED=(
     # Red Hat is the leading provider of enterprise open source software solutions.
     # <https://www.redhat.com/>
 
@@ -225,21 +225,21 @@ declare -r REDHAT_BASED=(
     "trustix" "wibni" "hancom" "xteam"
 )
 
-declare -r OPENSUSE_BASED=(
+readonly OPENSUSE_BASED=(
     # The makers' choice for sysadmins, developers and desktop users.
     # <https://www.opensuse.org/>
 
     "opensuse" "suse" "geckolinux" "linuxkamarada" "united" "kmlinux" "sunjds" "urix" "sle" "karamad" "jacklab" "stresslinux"
 )
 
-declare -r GUIX_BASED=(
+readonly GUIX_BASED=(
     # A complete GNU operating system harnessing all the capabilities of the Guix software. Spawned bu Guix itself.
     # <https://guix.gnu.org/>
 
     "guix"
 )
 
-declare -r FREEBSD_BASED=(
+readonly FREEBSD_BASED=(
     # FreeBSD is an operating system used to power modern servers, desktops, and embedded platforms.
     # <https://www.freebsd.org/>
 
@@ -248,7 +248,7 @@ declare -r FREEBSD_BASED=(
     "fireflybsd" "freesbie" "desktopbsd" "frenzy" "rofreesbie" "ging" "triance" "gulicbsd" "monowall" "pcbsd" "nas4free" "bsdrp"
 )
 
-declare -r OPENBSD_BASED=(
+readonly OPENBSD_BASED=(
     # Only two remote holes in the default install, in a heck of a long time!
     # <https://www.openbsd.org/>
 
@@ -256,14 +256,14 @@ declare -r OPENBSD_BASED=(
     "miros" "olivebsd" "psygnat" "quetzal" "sonafr" "hyperbolabsd" "aeriebsd" "anonymos" "utmfw" "gnobsd"
 )
 
-declare -r NETBSD_BASED=(
+readonly NETBSD_BASED=(
     # NetBSD is a free, fast, secure, and highly portable Unix-like Open Source operating system.
     # <https://www.netbsd.org/>
 
     "netbsd" "blackbsd" "edgebsd" "seos" "os108" "jibbed" "fdgw" "g4u" "irbsd" "smolbsd"
 )
 
-declare -r SOLARIS_ILLUMOS_BASED=(
+readonly SOLARIS_ILLUMOS_BASED=(
     # Oracle Solaris is the trusted business platform that you depend on. Oracle Solaris gives you consistent compatibility, is simple to use, and is designed to always be secure.
     # <https://www.oracle.com/solaris/solaris11/>
     #
@@ -274,7 +274,7 @@ declare -r SOLARIS_ILLUMOS_BASED=(
     "xstreamos"
 )
 
-declare -r MACOS_BASED=(
+readonly MACOS_BASED=(
     # If you can dream it, Mac can do it.
     # <https://www.apple.com/macos>
 
@@ -283,7 +283,7 @@ declare -r MACOS_BASED=(
 
 is_based_on() 
 {
-    local distro="${1,,}"
+    distro="${1,,}"
     shift
     [[ " $* " == *" $distro "* ]]
 }
@@ -305,7 +305,7 @@ is_macos_based()           { is_based_on "$1" $MACOS_BASED;           }
 
 get_user_distro()
 {
-    local id
+    id=
     
     if [[ -f /etc/os-release ]]; then
         while IFS="=" read -r key value; do
@@ -335,21 +335,20 @@ get_init_system()
 
 get_pid1_comm()
 {
-    local comm=$(ps -p 1 -o comm= 2>/dev/null)
+    comm=$(ps -p 1 -o comm= 2>/dev/null)
     printf "${comm}\n"
 }
 
 clear_screen()
 {
-    command -v clear >/dev/null 2>&1 && \
-        { clear; } || printf "${YELLOW}[!] Warning: 'clear' utility not found.${RESET}\n" >&2
+    tput clear
 }
 
 prompt_user()
 {
     shopt -s extglob
     
-    local prompt="$1" default="${2:-N}" user_input
+    prompt="$1" default="${2:-N}" user_input
     default="${default,,}"
     
     read -rp "$prompt (y/n) [${default^^}]: " user_input
@@ -367,7 +366,7 @@ prompt_user()
 check_privileges()
 {
     [[ "$EUID" -ne 0 ]] && \
-        { printf "${RED}[!] Error: This script requires root privileges to work.${RESET}\n" >&2; exit 1; } ||
+        { printf "${RED}[!] Error: Root privileges not present.${RESET}\n" >&2; return 1; } ||
         { printf "${GREEN}[*] Success! Root privileges are present.${RESET}\n" >&2; return 0; }
 }
 
@@ -380,8 +379,8 @@ check_privileges()
 ##
 _run_dinitctl()
 {
-    local action="$1"
-    local service="$2"
+    action="$1"
+    service="$2"
 
     dinitctl "$action" "$service" >/dev/null 2>&1 &&
         { printf "${GREEN}[*] Success!${RESET}\n"; return 0; } ||
@@ -414,8 +413,8 @@ signal_dinitctl()     { _run_dinitctl "signal"     "$1"; }
 
 execute_dinitctl()
 {
-    local command="$1"
-    local service="$2"
+    command="$1"
+    service="$2"
 
     case "$command" in
         "start" | "stop" | "status" | "is-started" | "is-failed" | "restart" | "wake" | "release" | \
@@ -429,7 +428,7 @@ execute_dinitctl()
             ;;
     esac
 
-    local func_name="${command//-/_}_dinitctl"
+    func_name="${command//-/_}_dinitctl"
     "$func_name" "$service"
 }
 
@@ -438,8 +437,8 @@ execute_dinitctl()
 ##
 _run_launchctl()
 {
-    local action="$1"
-    local service="$2"
+    action="$1"
+    service="$2"
 
     launchctl "$action" "$service" >/dev/null 2>&1 &&
         { printf "${GREEN}[*] Success!${RESET}\n"; return 0; } ||
@@ -489,8 +488,8 @@ help_launchctl()           { _run_launchctl "help"           "$1"; }
 
 execute_launchctl()
 {
-    local command="$1"
-    local service="$2"
+    command="$1"
+    service="$2"
 
     case "$command" in
         "bootstrap" | "bootout" | "enable" | "disable" | "uncache" | "kickstart" | "attach" | "debug" | \
@@ -506,7 +505,7 @@ execute_launchctl()
             ;;
     esac
 
-    local func_name="${command//-/_}_launchctl"
+    func_name="${command//-/_}_launchctl"
     "$func_name" "$service"
 }
 
@@ -515,8 +514,8 @@ execute_launchctl()
 ##
 _run_rc_service()
 {
-    local action="$1"
-    local service="$2"
+    action="$1"
+    service="$2"
 
     rc-service "$service" "$action" >/dev/null 2>&1 &&
         { printf "${GREEN}[*] Success!${RESET}\n"; return 0; } ||
@@ -533,8 +532,8 @@ status_rc_service()       { _run_rc_service "status"       "$1"; }
 
 execute_rc_service()
 {
-    local command="$1"
-    local service="$2"
+    command="$1"
+    service="$2"
 
     case "$command" in
         "start" | "stop" | "restart" | "reload" | "force-reload" | "try-restart" | "status")
@@ -546,7 +545,7 @@ execute_rc_service()
             ;;
     esac
 
-    local func_name="${command//-/_}_rc_service"
+    func_name="${command//-/_}_rc_service"
     "$func_name" "$service"
 }
 
@@ -555,8 +554,8 @@ execute_rc_service()
 ##
 _run_sv()
 {
-    local action="$1"
-    local service="$2"
+    action="$1"
+    service="$2"
 
     sv "$action" "$service" >/dev/null 2>&1 &&
         { printf "${GREEN}[*] Success!${RESET}\n"; return 0; } ||
@@ -591,8 +590,8 @@ check_sv()            { _run_sv "check"            "$1"; }
 
 execute_sv()
 {
-    local command="$1"
-    local service="$2"
+    command="$1"
+    service="$2"
 
     case "$command" in
         "status" | "up" | "down" | "once" | "pause" | "cont" | "hup" | "alarm" | "interrupt" | \
@@ -606,7 +605,7 @@ execute_sv()
             ;;
     esac
 
-    local func_name="${command//-/_}_sv"
+    func_name="${command//-/_}_sv"
     "$func_name" "$service"
 }
 
@@ -615,8 +614,8 @@ execute_sv()
 ##
 _run_s6_rc()
 {
-    local action="$1"
-    local service="$2"
+    action="$1"
+    service="$2"
 
     s6-rc "$action" "$service" >/dev/null 2>&1 &&
         { printf "${GREEN}[*] Success!${RESET}\n"; return 0; } ||
@@ -633,8 +632,8 @@ change_s6_rc()   { _run_s6_rc "change"   "$1"; }
 
 execute_s6_rc()
 {
-    local command="$1"
-    local service="$2"
+    command="$1"
+    service="$2"
 
     case "$command" in
     	"help" | "list" | "listall" | "diff" | "start" | "stop" | "change")
@@ -646,7 +645,7 @@ execute_s6_rc()
             ;;
     esac
 
-    local func_name="${command//-/_}_s6_rc"
+    func_name="${command//-/_}_s6_rc"
     "$func_name" "$service"
 }
 
@@ -655,8 +654,8 @@ execute_s6_rc()
 ##
 _run_systemctl()
 {
-    local action="$1"
-    local service="$2"
+    action="$1"
+    service="$2"
 
     systemctl "$action" "$service" >/dev/null 2>&1 &&
         { printf "${GREEN}[*] Success!${RESET}\n"; return 0; } ||
@@ -738,8 +737,8 @@ unset_environment_systemctl()      { _run_systemctl "unset-environment"         
 
 execute_systemctl()
 {
-    local command="$1"
-    local service="$2"
+    command="$1"
+    service="$2"
 
     case "$command" in
         "add-requires" | "add-wants" | "bind" | "cancel" | "cat" | "condreload" | "condrestart" | "condstop" | \
@@ -760,7 +759,7 @@ execute_systemctl()
         	;;
     esac
 
-    local func_name="${command//-/_}_systemctl"
+    func_name="${command//-/_}_systemctl"
     "$func_name" "$service"
 }
 
@@ -769,8 +768,8 @@ execute_systemctl()
 ##
 _run_service()
 {
-    local action="$1"
-    local service="$2"
+    action="$1"
+    service="$2"
 
     service "$service" "$action" >/dev/null 2>&1 &&
         { printf "${GREEN}[*] Success!${RESET}\n"; return 0; } ||
@@ -785,8 +784,8 @@ status_service()       { _run_service "status"       "$1"; }
 
 execute_service()
 {
-    local command="$1"
-    local service="$2"
+    command="$1"
+    service="$2"
 
     case "$command" in
         "start" | "stop" | "restart" | "force-reload" | "status")
@@ -798,25 +797,25 @@ execute_service()
             ;;
     esac
 
-    local func_name="${command//-/_}_service"
+    func_name="${command//-/_}_service"
     "$func_name" "$service"
 }
 
 #
 # Package Managers:
 #
-declare -r SAFE_ARG_PATTERN="^[a-zA-Z0-9@._/:+=-]+$"
+readonly SAFE_ARG_PATTERN="^[a-zA-Z0-9@._/:+=-]+$"
 
 is_safe_argument()
 {
-    local arg="$1"
+    arg="$1"
 
     [[ "$arg" =~ $SAFE_ARG_PATTERN ]] && return 0 || return 1
 }
 
 validate_command()
 {
-    local arg
+    arg=
 
     (( $# == 0 )) && { printf "${RED}[!] Error: Empty command.${RESET}\n" >&2; return 1; }
 
@@ -830,7 +829,7 @@ validate_command()
 
 execute()
 {
-    local cmd=("$@")
+    cmd=("$@")
 
     ! validate_command "${cmd[@]}" && return 1
 
@@ -1374,12 +1373,13 @@ pkgin_stats()                   { execute pkgin stats               "$@"; }
 ##
 ## `portage` (open for pull requests):
 ##
+emerge()                        { execute emerge                    "$@"; }
 
 ##
 ## `qi`:
 ##
-qi()          { execute qi 		"$@"; }
-qi_warn()     { execute qi warn 	"$@"; }
+qi()          { execute qi 		   "$@"; }
+qi_warn()     { execute qi warn    "$@"; }
 qi_install()  { execute qi install "$@"; }
 qi_remove()   { execute qi remove  "$@"; }
 qi_upgrade()  { execute qi upgrade "$@"; }
@@ -1569,7 +1569,7 @@ zypper_log() { execute zypper-log "$@"; }
 #
 main()
 {
-    local cmd="$1"
+    cmd="$1"
     
     [[ $# -gt 0 ]] && shift
 	[[ -z "$cmd" ]] && return
@@ -1592,17 +1592,16 @@ main()
             ;;
 
         "-v" | "--version")
-        	printf "$VERSION\n"
+            printf "$VERSION\n"
         	exit 0
         	;;
         *)
-            printf "${RED}[!] Can't understand what do you want.\n${RESET}Try checking '--help'.\n"
+            declare -F -- "$cmd" > /dev/null && \
+            "$cmd" "$@" || \
+            { printf "${RED}[!] Error invoking '$cmd' or unknown command '$cmd'.\nCheck '--help'.${RESET}\n" >&2; exit 1; }
             exit 0
             ;;
     esac
-
-     declare -F -- "$cmd" > /dev/null && \
-         "$cmd" "$@" || { printf "${RED}[!] Error invoking '$cmd' or unknown command '$cmd'.${RESET}\n" >&2; exit 1; }
 }
 
 [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
